### ISSUE TITLE
HCP (Human Connectome Project) support

### ISSUE THREAD

**Issue by mih** [datalad/datasets.datalad.org#10]
_From @yarikoptic on June 21, 2016 15:15_

Original implementation will just expose data as available from S3

Due to a vast size in terms of # of files etc, further modularization is needed, so submodules will be provided per each subject, and within subject for different pre-processing schemes etc

Related
- [ ] https://github.com/datalad/datalad/issues/2  XNAT support since data originally distributed from XNAT, and then mirrored into S3. WiP: #1552 
- [ ] https://github.com/datalad/datalad/issues/5 Aspera support
- [ ] https://github.com/datalad/datalad/issues/32 slow operations on indirect repos (might be better or worse with v6 style repos, yet to check)
- [ ] #1671 commands for checkout/merge on hierarchy of the datasets 

_Copied from original issue: datalad/datalad#579_

**Comment by mih** [comment]
@yarikoptic Together with @TobiasKadelka we are approaching this issue, with the goal of having an HCP dataset on http://datasets.datalad.org. It would be great to can an update on where we stand with this. Is there an tuned S3 crawler pipeline draft for HCP around somewhere?

At the moment we are planning for a dataset separation by participant (only, for now). We have a sizable chunk of it locally already and test a few different scenarios, if needed.

Thx!

**Comment by yarikoptic** [comment]
well, if we ignore inability to properly branch out for releases (hcp500, 900, ...), and indeed would do a subdataset per subject (which is still suboptimal since those are huge on their own), then there is nothing to do really, it seems to still work:
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl-misc/hcp/101006[hcp500]
$> datalad --dbg crawl                                                      
[WARNING] Failed to load entrypoint neuroimaging: (pybids 0.6.4 (/home/yoh/proj/datalad/datalad-crawler/venvs/dev/lib/python2.7/site-packages), Requirement.parse('pybids>=0.7.0')) [__init__.py:resolve:854] 
[INFO   ] Loading pipeline specification from ./.datalad/crawl/crawl.cfg 
[WARNING] Failed to load entrypoint neuroimaging: (pybids 0.6.4 (/home/yoh/proj/datalad/datalad-crawler/venvs/dev/lib/python2.7/site-packages), Requirement.parse('pybids>=0.7.0')) [__init__.py:resolve:854] 
[INFO   ] Creating a pipeline for the hcp-openaccess bucket 
[INFO   ] Running pipeline [<datalad_crawler.nodes.s3.crawl_s3 object at 0x7f869a300a10>, switch(default=None, key='datalad_action', mapping=<<{'commit': <function _...>>, re=False), <function _drop at 0x7f869a55fb18>] 
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication 
[INFO   ] Need to download 876 Bytes from s3://hcp-openaccess/HCP/101006/.xdlm/101006_3T_Diffusion_preproc.json?versionId=1NlM3Ap1CIgfQaOQcY4u3hDTlIbAQw7b. No progress indication will be reported 
[INFO   ] Need to download 4.6 kB from s3://hcp-openaccess/HCP/101006/.xdlm/101006_3T_Diffusion_unproc.json?versionId=lSlYeNBJCh5GvDqYHanbYuNleyccacca. No progress indication will be reported 

...
```
with just a regular stock s3 crawler:
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl-misc/hcp/101006[hcp500]
$> cat .datalad/crawl/crawl.cfg 
[crawl:pipeline]
template = simple_s3
_to_http = False
_prefix = HCP/101006/
_bucket = hcp-openaccess
_skip_problematic = False
_drop = True

$> cat ../.datalad/crawl/crawl.cfg
[crawl:pipeline]
template = simple_s3
_directory = subdataset
_bucket = hcp-openaccess
_prefix = HCP
```
after a tiny "not sure how it worked before" fix to crawler: https://github.com/datalad/datalad-crawler/pull/43

**Comment by mih** [comment]
Cool, thanks much!

**Comment by mih** [comment]
After datalad/datalad-crawler#43 I have the super pipeline running, but a see a mismatch in the subdataset crawler config. I get:

```
% cat 901442/.datalad/crawl/crawl.cfg
[crawl:pipeline]
template = simple_s3
_prefix = HCP/901442/
_bucket = hcp-openaccess
_to_http = False
_skip_problematic = False
```

How can I get the `_drop = True` into this config automatically?

**Comment by mih** [comment]
> inability to properly branch out for releases (hcp500, 900, ...)

I was looking into that. Here is something that I'd like to try: HCP500 should be a historical subset of HCP900 and the same for HCP1200. Spot-checking files for participants included in all releases seem to confirm that. We could crawl HCP500 first, and tag it. Then adjust the pipeline config to crawl HCP900, tag it. And finally go for HCP1200..

If there is ever any need to recrawl a prior release, we can branch off the respective tags.

It is different, however, for `HCP_Retest`. It uses the exact same dir/filenames as HCP500/900/1200, but the file content is different. I am uncertain how to present this best. Having it be its own superdataset seems to be the most sensible setup to me.

Q is now what dataset structure to use? Maybe this one

```
HCP
- HCP
- HCP_retest
```

alternatively:

```
HCP
- HCP500
- HCP900
- HCP1200
- HCP_retest
```

where the first three would share a subset of their subdatasets (participants). This would be a nice setup,  because it reflects the releases that people know about, but I think our tooling might not be ready for this, yet.

**Comment by mih** [comment]
https://github.com/datalad-datasets/human-connectome-project-openaccess

**Comment by adswa** [comment]
With the hcp dataset existing, is it okay to close this issue?

**Comment by mih** [comment]
I think so. Moreover, datalad-xnat can handle the connectomedb too.
